---
- name: Ansible resource module facts example
  hosts: sonic_devices
  gather_facts: false

  tasks:
    - name: "Gather facts"
      dellemc.enterprise_sonic.sonic_facts:
        gather_subset: min
        gather_network_resources:
          - interfaces
          - l3_interfaces
          - lag_interfaces
          - vlans
          - bgp
      register: result

    - name: "Debug facts"
      ansible.builtin.debug:
        msg: "{{ result.ansible_facts.ansible_network_resources }}"

...
