---
- name: Ansible resource module facts example
  hosts: sonic_devices
  gather_facts: false

  tasks:
    - name: "Gather facts"
      dellemc.enterprise_sonic.sonic_facts:
        gather_subset: min
        gather_network_resources:
          - interfaces
          - l2_interfaces
          - l3_interfaces
          - lag_interfaces
          - vlans
          - bgp
      register: result

    - name: Copy facts to file
      ansible.builtin.copy:
        content: "{{ result.ansible_facts.ansible_network_resources | to_nice_yaml }}"
        dest: "./host_vars/{{ inventory_hostname }}.yml"
          
...
